#################################################
# R Tutorial 
# Filename: 4-SourceSink.R
# Shankar Venkatagiri
#################################################

# First, set the proper working directory
# You know how to do it!

# Next, create a sub-directory for the output
dir.create("SinkEx")

# Start recording the output - basically runs the code in source file identified below
sink("SinkEx/NumPrimes", append=TRUE) # set file name and destination for text output
pdf("SinkEx/Graphs.pdf") # set file name and destination for graphs

source("1-Data.R") # select source file 

# Stop recording the output
sink()
dev.off()
print("We are done!")

# SinkEx directory now has 2 files
# NumPrimes contains Console output from running the R code in 1-Data.R
# Graphs.pdf contains the chart generated by running R code in 1-Data.R
# open the files from SinkEx directory to see

#### Neat! 